' Used in a bitmask, values match MMBasic gamepad constants.
const CTRL_START = &h02
const CTRL_DOWN  = &h20
const CTRL_RIGHT = &h40
const CTRL_UP    = &h80
const CTRL_LEFT  = &h100

const KB_SPACE=32
const KB_UP=128
const KB_DOWN=129
const KB_LEFT=130
const KB_RIGHT=131
const KB_ESC=27

const MAP_DIR="resources/map_levels/map01/"
const PLAYER_CAR_DIR="resources/vehicles/player_car/ferraris/ferrari01/"
